#!/bin/bash

set -ue

### important for making 'sort' and 'join' to be compatible
export LC_ALL=C

### require GNU awk (uses --assign and 3-argument match())
if ! awk --version 2>/dev/null | grep -qi "GNU Awk"; then
  echo "Error: GNU awk (gawk) is required, but 'awk' is not GNU Awk." >&2
  exit 1
fi

### CREate version (bumped at release time by release.sh; keep in sync with the git tag)
VERSION="0.2.1"


### define error message
usage()
{
  cat <<EOF

CREate version ${VERSION}

CREate is a software tool designed to identify cis-regulatory elements by analyzing transcription
initiation activity measured by CAGE (Cap Analysis of Gene Expression). Cis-regulatory elements,
such as promoters and enhancers, are characterized by active transcription and typically exhibit 
a divergent architecture. For example, promoters that produce mRNA and long noncoding RNA often 
generate upstream antisense RNA (uaRNA), while enhancers are frequently associated with bidirectional
transcription, although unidirectional patterns can also occur. Divergent transcription is thus 
a common hallmark of both promoters and enhancers.

Based on transcription initiation profiles, CREate detects genomic regions exhibiting non-convergent
transcription and classifies them as candidate cis-regulatory elements. Given a genomic position N and 
the transcription initiation profiles in both the sense and antisense directions, N is classified as 
divergent if the following condition is satisfied:


    [ left_rev + right_fwd ] > [ left_fwd + right_rev ] 
  
where

                     left        right

      forward     (left_fwd)     (right_fwd)
               -------------[N]----------------
      reverse    (left_rev)     (right_rev)

Requirements

* gawk (GNU awk; CREate uses --assign and 3-argument match(), tested in v5.x)
* samtools (https://github.com/samtools/samtools , tested in version 1.9)
* bedtools (https://github.com/arq5x/bedtools2 , tested in v2.29.2)
* jksrc (http://hgdownload.cse.ucsc.edu/admin/ , tested in v425; provides bedGraphToBigWig, bigWigAverageOverBed, bigWigMerge, bigWigToBedGraph)
* R (https://www.r-project.org/ , tested in v4.0.2)
* tidyverse (https://www.tidyverse.org/ , tested in v1.3.0)
* (STAR, to generate the input alignment)



## Usage

    $0 <subcommand> <args>



Subcommands

* bam2ctss : Generate CTSS (CAGE tag starting site) count file based on BAM alignment file
* run      : Run the peak call steps (total, call, filter, classify, eachcount) at once
* total    : Generate total CTSS count file based on multiple CTSS BED files
* call     : Call divergently transcribed regions as candidates of cis-regulatory elements 
* filter   : Filter the regions
* classify : Classify the regions to PLA (promoter level activity) or ELA (enhancer level activity)
* eachcount: Count reads belonging to the the divergently transcribed regions per sample
* version  : Print the CREate version


## bam2ctss

Generate CTSS (CAGE tag starting site) count file in BED format, from BAM alignment file

    $0 bam2ctss -i infile.star.bam -g genome.fa \\
        [-q mapQ (default:20)] \\
        [-p parallel (default:8)] \\
        [-w filter_window (default:20)] \\
        [-b filter_target_base (default:G; otheriwse N)] \\
        [-r ratio_Gaddition (default:0.89)] \\
        [-f full_set_of_intermediate_files (default: null)]

This subcommand counts capped RNA 5-ends at single-nucleotide resolution based on
CAGE (Cap Analysis of Gene Expression) read alignments. It selectively considers
reads that start with a genomically unencoded G (guanine), a hallmark of high-confidence
capped 5-ends (Science. 385(6704):eadd8394, 2024; Genome Res. 24(4):708-17, 2014).
However, accurately identifying such unencoded Gs involves technical challenges,
especially in regions where the genome itself also contains Gs near transcription start sites.

Determining whether a read carries an unencoded G can be difficult when the genomic
sequence immediately upstream (one nucleotide before the true TSS) also harbors G. 
To resolve this ambiguity, the subcommand examines the surrounding sequence within
a defined window to determine whether such reads should be retained or discarded.

Accurate identification of transcription start sites (TSSs) within G-stretch regions
is further complicated by ambiguity over whether the 5-end guanine is genomically encoded or 
the result of post-transcriptional G-addition. the subcommand applies a correction strategy 
by shifting a proportion of reads based on an assumed G-addition rate.

Note: The input file must be a BAM file generated by STAR (https://github.com/alexdobin/STAR) 
with the --alignEndsType Local option. This alignment mode ensures that mismatched ends,
particularly 5-ends, are treated as soft clips through local alignment.


## run

Run the peak call steps (total, call, filter, classify, eachcount) at once

    $0 run  \\
        -i infiles(comma separated) \\
        -c chrom_sizes \\
        -o out_prefix \\
        [-w window_size(default:200)] \\
        [-l min_length] \\
        [-n min_counts] \\
        [-t min_tpm] \\
        [-e PLA_or_ELA_threshold_in_TPM(default: 2)] \\
        [-p parallel(default:20)] \\
        [-z compress_decompress_program(default:gzip; zstd is recommended if available)]

Note that each of the input files should be BED-formatted CTSS profiles with gzip (*.ctss.bed.gz).
The resulting files are:

* out_prefix_param.txt
* out_prefix_{total|max}.ctss.{bed.gz|fwd.bw|rev.bw}
* out_prefix_each.ctss.bw.tar
* out_prefix_each.ctssTpm.bw.tar
* out_prefix_region.bed.gz
* out_prefix_region_filter_classify.bed.gz
* out_prefix_region_filter_classify_eachcounts.bed9pls3.gz
* out_prefix_region_filter_classify_eachcounts_totals.txt
* out_prefix_region_filter_classify_eachcounts.txt.gz


## total

Generate total CTSS count file based on multiple CTSS BED files

    $0 total \\
        -i infiles(comma separated) \\
        -c chrom_sizes \\
        -o out_prefix \\
        [-p parallel(default:20)]

which produces the following files:

* PREFIX_total.ctss.{bed.gz|fwd.bw|rev.bw}
* PREFIX_max.ctss.{bed.gz|fwd.bw|rev.bw}


## call

Call divergently transcribed regions as candidates of cis-regulatory elements 

    $0 call \\
        -i infile.ctss.bed.gz \\
        -c chrom_sizes \\
        [-w window_size(default:200)] \\
        [-m outfileMax.ctss.bed.gz] \\
        [-p parallel(default:20)] \\
        [-z compress_decompress_program(default:gzip; zstd is recommended if available)] \\
    | gzip -c > output.bed.gz


The output file is formatted in BED9, where the thickStart/thickEnd specify 'core' region which is
predominantly divergent('#') and the start/end specify the region where signals considered ('+'). 
The 'core' regions do not overlap each other, while the signal considered region may. The 5th (score)
column indicates CRE activity based on TPM (transcripts per million).

            ffffffffffff
       +++++########++++
       rrrrrrrrrrrrr

Forward signals are indicated in 'f' and reverse signals in 'r'. The 'core' regions are
non-overlapping, whereas the signal-considered regions may overlap.


## filter

Filter the regions

    gunzip -c output.bed.gz \\
    | $0 filter \\
        [-D max_directionality(default:1)] \\
        [-d min_directionality(default:0)] \\
        [-C max_counts(default:-1)] \\
        [-c min_counts(default:4)] \\
        [-T max_tpm(default:-1)] \\
        [-t min_tpm(default:0)] \\
        [-e min_counts_in_each_strand(default:0)] \\
        [-x min_ctssMax(default:0)] \\
        [-y min_ctssMax_in_each_strand(default:0)] \\
        [-L max_length(default:-1)] \\
        [-l min_length(default:5)] \\
        [-v] (for invert match, such as "grep -v")

Filtering based on expression (-t TPM) is recommended, 
where 0.05 and 0.5 are reasonable for CAGE.


## classify

Classify the regions to PLA (promoter level activity) or ELA (enhancer level activity)

    gunzip -c output.bed.gz \\
    | $0 classify \\
        [-e PLA_or_ELA_threshold_in_TPM (default: 2)]


## eachcount

Count reads belonging to the the divergently transcribed regions per sample

    $0 eachcount \\
        -i divergently_transcribed_region.bed.gz  (BED9 format) \\
        -e infile_each.ctss.bw.tar (archive of bigWig files for each strand) \\
        -o out_prefix \\
        [-p parallel(default:20)]


## Author

KAWAJI, Hideya <h.kawaji@gmail.com>


EOF
  exit 1;
}



#-------------------------------------
# functions
#-------------------------------------


### Bam to CTSS with unencoded G selection (REAP+) and G correction
function splitBam2UnmatchMatchOthers()
{
  # init
  samtools view -H ${infile} > ${tmpdir}/fwd_unmatchG.sam
  samtools view -H ${infile} > ${tmpdir}/fwd_matchG.sam
  samtools view -H ${infile} > ${tmpdir}/fwd_matchH.sam
  samtools view -H ${infile} > ${tmpdir}/fwd_others.sam
  samtools view -H ${infile} > ${tmpdir}/rev_unmatchG.sam
  samtools view -H ${infile} > ${tmpdir}/rev_matchG.sam
  samtools view -H ${infile} > ${tmpdir}/rev_matchH.sam
  samtools view -H ${infile} > ${tmpdir}/rev_others.sam
  samtools view -H ${infile} \
  | awk '{match($0, /SN:([a-zA-Z0-9_\.\-\+#@!&%]+)\s+LN:([0-9]+)/, buf); if(RLENGTH>=0){print buf[1]"\t"buf[2]}}' \
  > ${tmpdir}/chrom_sizes

  # fwd
  samtools view -F 16 -q ${mapQ} ${infile} \
  | awk \
      --assign fileU=${tmpdir}/fwd_unmatchG.sam \
      --assign fileM=${tmpdir}/fwd_matchG.sam  \
      --assign fileH=${tmpdir}/fwd_matchH.sam  \
      --assign fileO=${tmpdir}/fwd_others.sam  \
    '{
      unmatchN = "";matchN = "";
      match($6,/^([0-9]+)S/,buf)

      if (RLENGTH>=0){ unmatchN = substr($10,0,buf[1]) }
      else{ matchN = substr($10,0,1) }

      if (unmatchN == "G") { print $0 >> fileU }
      else if (matchN == "G") { print $0 >> fileM }
      else if (matchN != "") { print $0 >> fileH }
      else { print $0 >> fileO }
    }'

  # rev
  samtools view -f 16 -q ${mapQ} ${infile} \
  | awk \
      --assign fileU=${tmpdir}/rev_unmatchG.sam \
      --assign fileM=${tmpdir}/rev_matchG.sam  \
      --assign fileH=${tmpdir}/rev_matchH.sam  \
      --assign fileO=${tmpdir}/rev_others.sam  \
    '{
      unmatchN = "";matchN = "";
      match($6,/([0-9]+)S$/,buf)

      if (RLENGTH>=0){unmatchN = substr($10, length($10) - buf[1] + 1) }
      else { matchN = substr($10,length($10) ) }

      if (unmatchN == "C") {print $0 >> fileU }
      else if (matchN == "C") {print $0 >> fileM }
      else if (matchN != "")  {print $0 >> fileH }
      else {print $0 >> fileO }
    }'

  # post processing
  for X in \
    ${tmpdir}/fwd_unmatchG.sam \
    ${tmpdir}/fwd_matchG.sam  \
    ${tmpdir}/fwd_matchH.sam  \
    ${tmpdir}/fwd_others.sam \
    ${tmpdir}/rev_unmatchG.sam \
    ${tmpdir}/rev_matchG.sam  \
    ${tmpdir}/rev_matchH.sam  \
    ${tmpdir}/rev_others.sam
  do
    cat $X \
    | bamToBed \
    | sort -k1,1 -k2,2n --parallel=$parallel \
    | genomeCoverageBed -5 -bg -i - -g ${tmpdir}/chrom_sizes \
    > ${X}.bg

    bedGraphToBigWig ${X}.bg ${tmpdir}/chrom_sizes ${X}.bw
  done
}


function correctG_fwd()
{
  # input: chrom=$1;start=$2;end=$3;U=$4;M=$5;vU=$6;vM=$7;vH=$8;nuc=$9;
  grep -v ^# \
  | awk --assign ratio_Gaddition=$ratio_Gaddition --assign filter_target_base=$filter_target_base \
    'BEGIN{
      OFS="\t"
      r = (1 / ratio_Gaddition) * (1 - ratio_Gaddition)
      prevU=0;prevM=0;prevN=0;prevNuc="";prevChrom="";prevStart=-1;
    }{
      N = 0
      chrom=$1; start=$2; end=$3;
      U=$4; M=$5; wU=$6; wM=$7; wH=$8; nuc=$9;

      if (prevChrom != chrom)
      {
        prevU=0;prevM=0;prevN=0;prevNuc="";prevChrom="";prevStart=-1
      }

      if ( (prevStart + 1) != start )
      {
        if ( (prevNuc == "G") || (prevNuc == "g") )
        {
          N = int( prevM - prevN * r )
          if (N < 0){ N = 0 }
          if (prevWU <= prevWH){ N = 0 }
          if ((filter_target_base == "N") && (prevWU <= prevWH)){ N = 0 }
          print prevChrom, prevStart+1, prevStart+2, 0, 0, prevWU, prevWM, prevWH, "*", N, 0
        }
        N = U

      } else if (( prevNuc != "G" ) && (prevNuc != "g" )) {

        N = U

      } else {

        N = int( prevM - prevN * r )
        if (N < 0){ N = 0 }
        if ((filter_target_base == "G") && (wU <= wH)){ N = 0 }

      }
      if ((filter_target_base == "N") && (wU <= wH)){ N = 0 }

      print $0, N, (N == U)
      prevChrom=chrom; prevStart=start;
      prevU  = U ; prevM  = M ;
      prevWU = wU; prevWM = wM; prevWH = wH;
      prevN = N; prevNuc = nuc;
  }'
}


function correctG_rev()
{
  # input: chrom=$1;start=$2;end=$3;U=$4;M=$5;vU=$6;vM=$7;vH=$8;nuc=$9;
  grep -v ^# \
  | awk --assign ratio_Gaddition=$ratio_Gaddition --assign filter_target_base=$filter_target_base \
    'BEGIN{
      OFS="\t"
      r = (1 / ratio_Gaddition) * (1 - ratio_Gaddition)
      prevU=0;prevM=0;prevN=0;prevNuc="";prevChrom="";prevStart=-1;
    }{
      N = 0
      chrom=$1;start=$2;end=$3;
      U=$4; M=$5; wU=$6; wM=$7; wH=$8; nuc=$9;

      if (prevChrom != chrom)
      {
        prevU=0;prevM=0;prevN=0;prevNuc="";prevChrom="";prevStart=-1
      }

      if ( (prevStart - 1) != start )
      {
        if ( (prevNuc == "C") || (prevNuc == "c") )
        {
          N = int( prevM - prevN * r )
          if (N < 0){ N = 0 }
          if (prevWU <= prevWH){ N = 0 }
          if ((filter_target_base == "N") && (prevWU <= prevWH)){ N = 0 }
          print chrom, prevStart-1, prevStart, 0, 0, prevWU, prevWM, prevWH, "*", N, 0
        }
        N = U

      } else if (( prevNuc != "C" ) && (prevNuc != "c" )) {

        N = U

      } else {

        N = int( prevM - prevN * r )
        if (N < 0){ N = 0 }
        if ((filter_target_base == "G") && (wU <= wH)){ N = 0 }

      }
      if ((filter_target_base == "N") && (wU <= wH)){ N = 0 }

      print $0, N, (N == U)
      prevChrom=chrom; prevStart=start;
      prevU = U; prevM = M;
      prevWU = wU; prevWM = wM; prevWH = wH;
      prevN = N; prevNuc = nuc;
  }'
}


function correctG()
{
  printf "___correctG:fwd:prep___\n" >&2

  cat ${tmpdir}/fwd_unmatchG.sam.bg \
      ${tmpdir}/fwd_matchG.sam.bg \
  | cut -f 1-3 \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  | mergeBed \
  | awk 'BEGIN{OFS="\t"}{
      for (i = $2; i < $3; i++){ name=$1","i","i+1; print $1, i, i+1, name}
    }' \
  > ${tmpdir}/fwd_target.bed

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/fwd_unmatchG.sam.bw ${tmpdir}/fwd_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/fwd_target.bed.wUnmatchG.bg

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/fwd_matchG.sam.bw ${tmpdir}/fwd_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/fwd_target.bed.wMatchG.bg

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/fwd_matchH.sam.bw ${tmpdir}/fwd_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/fwd_target.bed.wMatchH.bg

  unionBedGraphs -i \
    ${tmpdir}/fwd_unmatchG.sam.bg \
    ${tmpdir}/fwd_matchG.sam.bg \
    ${tmpdir}/fwd_target.bed.wUnmatchG.bg \
    ${tmpdir}/fwd_target.bed.wMatchG.bg \
    ${tmpdir}/fwd_target.bed.wMatchH.bg \
  | nucBed -fi ${genome_fa} -seq -bed - \
  > ${tmpdir}/fwd_target.bed.unmatchG_matchG_wUnmatchG_wMatchG_wMatchH_nuc.bg

  printf "___correctG:fwd:main___\n" >&2
  cat ${tmpdir}/fwd_target.bed.unmatchG_matchG_wUnmatchG_wMatchG_wMatchH_nuc.bg \
  | cut -f 1-8,18 \
  | correctG_fwd \
  > ${tmpdir}/fwd_correctG.txt



  printf "___correctG:rev:prep___\n" >&2

  cat ${tmpdir}/rev_unmatchG.sam.bg \
      ${tmpdir}/rev_matchG.sam.bg \
  | cut -f 1-3 \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  | mergeBed \
  | awk 'BEGIN{OFS="\t"}{
      for (i = $2; i < $3; i++){ name=$1","i","i+1; print $1, i, i+1, name}
    }' \
  > ${tmpdir}/rev_target.bed

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/rev_unmatchG.sam.bw ${tmpdir}/rev_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/rev_target.bed.wUnmatchG.bg

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/rev_matchG.sam.bw ${tmpdir}/rev_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/rev_target.bed.wMatchG.bg

  bigWigAverageOverBed -sampleAroundCenter=$filter_window \
    ${tmpdir}/rev_matchH.sam.bw ${tmpdir}/rev_target.bed /dev/stdout  \
  | cut -f 1,4 \
  | sed -e 's/,/\t/g' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/rev_target.bed.wMatchH.bg

  unionBedGraphs -i \
    ${tmpdir}/rev_unmatchG.sam.bg \
    ${tmpdir}/rev_matchG.sam.bg \
    ${tmpdir}/rev_target.bed.wUnmatchG.bg \
    ${tmpdir}/rev_target.bed.wMatchG.bg \
    ${tmpdir}/rev_target.bed.wMatchH.bg \
  | nucBed -fi ${genome_fa} -seq -bed - \
  > ${tmpdir}/rev_target.bed.unmatchG_matchG_wUnmatchG_wMatchG_wMatchH_nuc.bg


  printf "___correctG:fwd:main___\n" >&2

  cat ${tmpdir}/rev_target.bed.unmatchG_matchG_wUnmatchG_wMatchG_wMatchH_nuc.bg \
  | cut -f 1-8,18 \
  | sort -k1,1 -k2,2nr --parallel=$parallel \
  | correctG_rev \
  > ${tmpdir}/rev_correctG.txt



  printf "___correctG:post process___\n" >&2

  cat ${tmpdir}/fwd_correctG.txt \
  | cut -f 1,2,3,10 \
  | awk '{if($4>0){print}}' \
  > ${tmpdir}/fwd_correctG.bg
  bedGraphToBigWig ${tmpdir}/fwd_correctG.bg ${tmpdir}/chrom_sizes ${tmpdir}/fwd_correctG.bw

  cat ${tmpdir}/rev_correctG.txt \
  | cut -f 1,2,3,10 \
  | awk '{if($4>0){print}}' \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  > ${tmpdir}/rev_correctG.bg
  bedGraphToBigWig ${tmpdir}/rev_correctG.bg ${tmpdir}/chrom_sizes ${tmpdir}/rev_correctG.bw

  cat ${tmpdir}/fwd_correctG.bg \
  | awk 'BEGIN{OFS="\t"}{name=$1","$2","$3",+"; print $1,$2,$3,name,$4,"+"}' \
  > ${tmpdir}/correctG_raw.bed
  cat ${tmpdir}/rev_correctG.bg \
  | awk 'BEGIN{OFS="\t"}{name=$1","$2","$3",-"; print $1,$2,$3,name,$4,"-"}' \
  >> ${tmpdir}/correctG_raw.bed

  cat ${tmpdir}/correctG_raw.bed \
  | sort -k1,1 -k2,2n --parallel=$parallel \
  | gzip -c \
  > ${tmpdir}/correctG.bed.gz
  rm -f ${tmpdir}/correctG_raw.bed
}



###
### for peak calling
###

ctssbed_to_bg ()
{
  local strand=$1

  awk --assign strand=$strand 'BEGIN{OFS="\t"}{
    if($6 == strand )
    {
      for (i=$2; i < $3; i++) 
      {
        print $1,i,i+1,$5
      }
    }
  }' \
  | sort $SORT_OPT_BED
}


ctssGzBed_to_TpmBg ()
{
  local infile=$1
  local strand=$2

  total=$( gunzip -c $infile | awk '{total += $5 * ($3 - $2)}END{print total}' )
  gunzip -c $infile \
  | ctssbed_to_bg $strand \
  | awk --assign total=$total \
      '{$4 = $4 * 1e6 / total ; printf "%s\t%d\t%d\t%.2f\n", $1, $2, $3, $4}'
}



bg_to_bed4 ()
{
  awk 'BEGIN{OFS="\t"}{print $1,$2,$3,$1"|"$2"|"$3}'
}


ctss_density ()
{
  local infile_bed4=$1
  local infile_bw=$2
  local density_width=$3
  local outfile_bg=$4

  cat ${chrom_sizes} \
  | awk --assign density_width=$density_width 'BEGIN{OFS="\t"}{print $1, density_width, $2 - density_width}' \
  > ${infile_bed4}.tmp.scope

  intersectBed -u -wa -a ${infile_bed4} -b ${infile_bed4}.tmp.scope \
  | split -l ${splitLines} - ${infile_bed4}.tmp.non_boundary.split.

  ls ${infile_bed4}.tmp.non_boundary.split.* \
  | xargs -P ${parallel} -I % bigWigAverageOverBed -sampleAroundCenter=$density_width $infile_bw % %.OUT

  cat ${infile_bed4}.tmp.non_boundary.split.*.OUT \
  | cut -f 1,5 \
  | sed -e 's/|/\t/g' \
  | sort $SORT_OPT_BED \
  > ${outfile_bg}

  rm -f ${infile_bed4}.tmp.non_boundary.split.*
}



# --- prepare the following files ---
# ${tmpdir}/infile.fwd.bg
# ${tmpdir}/infile.rev.bg
# ${tmpdir}/infile.fwd.bw
# ${tmpdir}/infile.rev.bw
# ${tmpdir}/infile.density.fwd.bg
# ${tmpdir}/infile.density.rev.bg
# ${tmpdir}/infile.density.fwd.bw
# ${tmpdir}/infile.density.rev.bw
# ${tmpdir}/potential_center.bg.COMP
prep_input ()
{
  local infile=$1
  local window_double_size=$2
  local density_width=20

  gunzip -c ${infile} | ctssbed_to_bg + > ${tmpdir}/infile.fwd.bg
  gunzip -c ${infile} | ctssbed_to_bg - > ${tmpdir}/infile.rev.bg
  bedGraphToBigWig ${tmpdir}/infile.fwd.bg $chrom_sizes ${tmpdir}/infile.fwd.bw
  bedGraphToBigWig ${tmpdir}/infile.rev.bg $chrom_sizes ${tmpdir}/infile.rev.bw

  cat ${tmpdir}/infile.fwd.bg | bg_to_bed4 > ${tmpdir}/infile.fwd.bed4
  cat ${tmpdir}/infile.rev.bg | bg_to_bed4 > ${tmpdir}/infile.rev.bed4

  ctss_density \
    ${tmpdir}/infile.fwd.bed4 \
    ${tmpdir}/infile.fwd.bw \
    ${density_width} \
    ${tmpdir}/infile.density.fwd.bg

  ctss_density \
    ${tmpdir}/infile.rev.bed4 \
    ${tmpdir}/infile.rev.bw \
    ${density_width} \
    ${tmpdir}/infile.density.rev.bg

  bedGraphToBigWig ${tmpdir}/infile.density.fwd.bg $chrom_sizes ${tmpdir}/infile.density.fwd.bw
  bedGraphToBigWig ${tmpdir}/infile.density.rev.bg $chrom_sizes ${tmpdir}/infile.density.rev.bw

  sort $SORT_OPT_BED ${tmpdir}/infile.fwd.bg ${tmpdir}/infile.rev.bg \
  | mergeBed  -i stdin -d $window_double_size \
  | awk 'BEGIN{OFS="\t"}{ for (i=$2;i<$3;i++){print $1,i,i+1,$4} }' \
  | $PROG_COMP \
  > ${tmpdir}/potential_center.bg.COMP
}



acc_left ()
{
  local infile_bw=$1
  local chrom_sizes=$2
  local window_size=$3
  local outfile=$4
  awk 'BEGIN{OFS="\t"}{name=$1"|"$2"|"$3; print $1,$2,$3,name}' \
  | slopBed -i - -g $chrom_sizes -l $window_size -r 0 \
  | bigWigAverageOverBed $infile_bw /dev/stdin $outfile
}



acc_right ()
{
  local infile_bw=$1
  local chrom_sizes=$2
  local window_size=$3
  local outfile=$4
  awk 'BEGIN{OFS="\t"}{name=$1"|"$2"|"$3; print $1,$2,$3,name}' \
  | slopBed -i - -g $chrom_sizes -l 0 -r $window_size \
  | bigWigAverageOverBed $infile_bw /dev/stdin $outfile
}



acc_lr ()
{
  local lr=$1
  local infile_bw=$2
  local chrom_sizes=$3
  local window_size=$4
  local outfile=$5

  if [ "${lr}" = "left" ]; then
    awk 'BEGIN{OFS="\t"}{name=$1"|"$2"|"$3; print $1,$2,$3,name}' \
    | slopBed -i - -g $chrom_sizes -l $window_size -r 0 \
    | bigWigAverageOverBed $infile_bw /dev/stdin $outfile
  elif [ "${lr}" = "right" ]; then
    awk 'BEGIN{OFS="\t"}{name=$1"|"$2"|"$3; print $1,$2,$3,name}' \
    | slopBed -i - -g $chrom_sizes -l 0 -r $window_size \
    | bigWigAverageOverBed $infile_bw /dev/stdin $outfile
  else
    printf "acc_lr: no operation" >&2
  fi
}




# accumulate signals for (left | right) x (forward | reverse)
accumulate_neiboring_signals () 
{
  local infile_center=$1
  local infile_fwd_bw=$2
  local infile_rev_bw=$3
  local window_size=$4

  declare -A infile_bw
  infile_bw["fwd"]=$infile_fwd_bw
  infile_bw["rev"]=$infile_rev_bw

  for lr in left right
  do
    for strand in fwd rev
    do

      cat $infile_center | $PROG_DECOMP > ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.DECOMP

      chunkN=$(expr $( cat ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.DECOMP | wc -l ) / $splitLines + 1 )
      split -n "r/${chunkN}" \
        ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.DECOMP  \
        ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.
      rm -f ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.DECOMP &

      export -f acc_lr
      infbw=${infile_bw[${strand}]}
      ls ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.* \
      | xargs -P ${parallel} -I % bash -c "cat % | acc_lr ${lr} $infbw $chrom_sizes $window_size %.OUT"

      cat ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.*.OUT \
      | cut -f 1,4 \
      > ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.OUT.CONCAT

      sort $SORT_OPT_NAME ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.OUT.CONCAT \
      | $PROG_COMP \
      > ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.COMP

      rm -f ${tmpdir}/accumulate_neiboring_signals_${lr}_${strand}.txt.split.* &
    done
  done

  wait

  cat ${tmpdir}/accumulate_neiboring_signals_left_fwd.txt.COMP \
  | $PROG_DECOMP \
  | join -t "	" /dev/stdin <( cat ${tmpdir}/accumulate_neiboring_signals_left_rev.txt.COMP  | $PROG_DECOMP ) \
  | join -t "	" /dev/stdin <( cat ${tmpdir}/accumulate_neiboring_signals_right_fwd.txt.COMP | $PROG_DECOMP ) \
  | join -t "	" /dev/stdin <( cat ${tmpdir}/accumulate_neiboring_signals_right_rev.txt.COMP | $PROG_DECOMP )

}



classify_convergent_divergent ()
{
  local outfile_convergent=$1
  local outfile_divergent=$2

  awk \
    --assign outfile_convergent=$outfile_convergent \
    --assign outfile_divergent=$outfile_divergent \
  '{
    left_fwd = $2; left_rev = $3; right_fwd = $4; right_rev = $5;

    if ( (left_rev + right_fwd)  == 0 ) { next }
    convergency = (left_fwd + right_rev) / (left_rev + right_fwd) 
    if ( convergency > 1 ) { print > outfile_convergent".txt"; next}
    print > outfile_divergent".txt"
  }'

  cat ${outfile_convergent}".txt" \
  | sed -e 's/|/\t/g' | cut -f 1-3 | sort $SORT_OPT_BED \
  | mergeBed -i stdin \
  > ${outfile_convergent}

  cat ${outfile_divergent}".txt" \
  | sed -e 's/|/\t/g' | cut -f 1-3 | sort $SORT_OPT_BED \
  | mergeBed -i stdin \
  > ${outfile_divergent}
}



find_max_score_in_left () {
  local infile_bg=$1
  local extend_size=$2

  awk --assign extend_size=$extend_size 'BEGIN{OFS="\t"}{
    name=$1"|"$2"|"$3;
    start = $2 - extend_size;
    if (start < 0) {start = 0}
    print $1, start, $3, name
  }' \
  | sort $SORT_OPT_BED \
  | intersectBed -sorted -wa -wb -a stdin -b ${infile_bg} \
  | groupBy -grp 4 -opCols 5,6,7,8 -ops collapse \
  | awk 'BEGIN{OFS="\t"}{
      orig_n = split($1, orig_a, "|")
      chr_n = split($2, chr_a, ",")
      start_g = split($3, start_a, ",")
      stop_n = split($4, stop_a, ",")
      score_n = split($5, score_a, ",")

      chr = orig_a[1]; score = 0;
      start = orig_a[2]; stop = start + 1;
      leftmost_start = start;
      for (i=1; i<=score_n; i++)
      { 
        ### max score
        if ( score < score_a[i] )
        {
          chr = chr_a[i]; score = score_a[i];
          start = start_a[i]; stop = stop_a[i];
        } else if (( score == score_a[i]) && (start < start_a[i])) {
          chr = chr_a[i]; score = score_a[i];
          start = start_a[i]; stop = stop_a[i];
        }
        ### leftmost
        if (( score_a[i] > 0 ) && ( start_a[i] < leftmost_start ))
        {
          leftmost_start = start_a[i]
        }
      }
      print $1, chr"|"start"|"stop"|"score"|leftmost_start|"leftmost_start
    }'
}



find_max_score_in_right () {
  local infile_bg=$1
  local extend_size=$2

  awk --assign extend_size=$extend_size 'BEGIN{OFS="\t"}{
    name=$1"|"$2"|"$3;
    print $1,$2,$3 + extend_size,name
  }' \
  | sort $SORT_OPT_BED \
  | intersectBed -sorted -wa -wb -a stdin -b ${infile_bg} \
  | groupBy -grp 4 -opCols 5,6,7,8 -ops collapse \
  | awk 'BEGIN{OFS="\t"}{
      orig_n = split($1, orig_a, "|")
      chr_n = split($2, chr_a, ",")
      start_n = split($3, start_a, ",")
      stop_n = split($4, stop_a, ",")
      score_n = split($5, score_a, ",")

      chr = orig_a[1]; score = 0;
      stop = orig_a[3]; start = stop - 1;
      rightmost_stop = stop;
      for (i=1; i<=score_n; i++)
      {
        ### max score
        if ( score_a[i] > score )
        {
          chr = chr_a[i]; score = score_a[i];
          start = start_a[i]; stop = stop_a[i];
        } else if (( score == score_a[i]) && (start > start_a[i])) {
          chr = chr_a[i]; score = score_a[i];
          start = start_a[i]; stop = stop_a[i];
        }
        ### rightmost
        if (( score_a[i] > 0 ) && ( stop_a[i] > rightmost_stop ))
        {
          rightmost_stop = stop_a[i]
        }
      }
      print $1, chr"|"start"|"stop"|"score"|rightmost_stop|"rightmost_stop
  }'
}



find_max_scores () {
  local infile=$1
  local infile_density_fwd_bg=$2
  local infile_density_rev_bg=$3
  local window_size=$4

  cat $infile \
  | find_max_score_in_left ${infile_density_rev_bg} ${window_size} \
  | sort $SORT_OPT_NAME \
  > ${tmpdir}/find_max_scores_left.txt &

  cat $infile \
  | find_max_score_in_right ${infile_density_fwd_bg} ${window_size} \
  | sort $SORT_OPT_NAME \
  > ${tmpdir}/find_max_scores_right.txt &

  wait


  cat ${tmpdir}/find_max_scores_left.txt ${tmpdir}/find_max_scores_right.txt \
  | cut -f 1 \
  | sort $SORT_OPT_NAME \
  | uniq \
  | join -j 1 -t "	" -a 1 -o 1.1,2.2     -e "NA|NA|NA|NA|NA|NA" - ${tmpdir}/find_max_scores_left.txt \
  | join -j 1 -t "	" -a 1 -o 1.1,1.2,2.2 -e "NA|NA|NA|NA|NA|NA" - ${tmpdir}/find_max_scores_right.txt \
  > ${tmpdir}/find_max_scores.txt

  cat ${tmpdir}/find_max_scores.txt \
  | sed -e 's/|/\t/g' \
  | awk 'BEGIN{OFS="\t"}{
      chr = $1; start = $2; stop = $3;

      chrL = $4; startL = $5; stopL = $6;
      scoreL = $7; leftmost = $9;
      if  (chrL == "NA")
      {
        chrL = chr; startL = start; stopL = stop; 
        scoreL = 0; leftmost = start;
      }

      chrR = $10; startR = $11; stopR = $12;
      scoreR = $13; rightmost = $15;
      if ( chrR == "NA")
      {
        chrR = chr; startR = start; stopR = stop;
        scoreR = 0; rightmost = stop;
      }

      if ( ( leftmost < rightmost ) && (startL < stopR) )
      {
        oChr = chr; oStart = leftmost; oStop = rightmost;
        thickStart = startL; thickStop = stopR;

      } else {
        oChr = chr; oStart = start; oStop = stop
        thickStart = start; thickStop = stop;
      }
      print oChr, oStart, oStop, ".", 0, ".", thickStart, thickStop, "0,0,0"
    }' \
  > ${tmpdir}/find_max_scores.bed

  cat ${tmpdir}/find_max_scores.bed \
  | awk 'BEGIN{OFS="\t"}{print $1,$7,$8,$2","$3}' \
  | sort $SORT_OPT_BED \
  | mergeBed -i stdin -c 4 -o collapse \
  | awk 'BEGIN{OFS="\t"}{
      chr = $1
      pos_n = split($4,pos_a,",")
      start = pos_a[1]
      stop = pos_a[1]
      for (i = 2; i<= pos_n; i++)
      {
        if (start > pos_a[i] ) { start = pos_a[i] }
        if (stop < pos_a[i] ) { stop = pos_a[i] }
      }
      name = chr","start","stop
      print chr, start, stop, name, 0, ".", $2, $3, "0,0,0"
    }'
}


tighten_unidirectional ()
{
  local infile=$1

  cat $infile \
  | cut -f 1-4 \
  | sort $SORT_OPT_BED \
  | uniq \
  > ${tmpdir}/trim_unidirectional.outbound.bed

  bigWigAverageOverBed \
    ${tmpdir}/infile.fwd.bw \
    ${tmpdir}/trim_unidirectional.outbound.bed \
    /dev/stdout \
  | awk '{if($4 == 0){print $1}}' \
  | sed -e 's/,/\t/g' \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3, $1","$2","$3 }' \
  | sort $SORT_OPT_BED \
  | intersectBed -sorted -wa -wb -a - -b ${tmpdir}/infile.rev.bg \
  | groupBy -g 1,2,3,4 -c 7 -o collapse \
  | cut -f 4,5 \
  | awk 'BEGIN{OFS="\t"}{
      stop_n = split($2,stop_a,",")
      rightmost = stop_a[1]
      for (i=2;i<=stop_n;i++)
      {
        if (rightmost < stop_a[i]) { rightmost = stop_a[i]}
      }
      print $1,"rightmost",rightmost
    }' \
  > ${tmpdir}/trim_unidirectional.outbound.adjust.txt

  bigWigAverageOverBed \
    ${tmpdir}/infile.rev.bw \
    ${tmpdir}/trim_unidirectional.outbound.bed \
    /dev/stdout \
  | awk '{if($4 == 0){print $1}}' \
  | sed -e 's/,/\t/g' \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3, $1","$2","$3}' \
  | sort $SORT_OPT_BED \
  | intersectBed -sorted -wa -wb -a - -b ${tmpdir}/infile.fwd.bg \
  | groupBy -g 1,2,3,4 -c 6 -o collapse \
  | cut -f 4,5 \
  | awk 'BEGIN{OFS="\t"}{
      start_n = split($2,start_a,",")
      leftmost = start_a[1]
      for (i=2;i<=start_n;i++)
      {
        if (leftmost > start_a[i]) { leftmost = start_a[i]}
      }
      print $1,"leftmost",leftmost
    }' \
  >> ${tmpdir}/trim_unidirectional.outbound.adjust.txt

  cat ${tmpdir}/trim_unidirectional.outbound.adjust.txt \
  | sort $SORT_OPT_NAME \
  > ${tmpdir}/trim_unidirectional.outbound.adjust.txt.sort

  cat $infile \
  | sort $SORT_OPT_BED_NAME \
  | join -1 4 -2 1 -a 1 -t "	" - ${tmpdir}/trim_unidirectional.outbound.adjust.txt.sort \
  | awk 'BEGIN{OFS="\t"}{
      name = $1; chr = $2; start = $3; stop = $4;
      score = $5 ; strand = $6; thickStart = $7; thickStop = $8;
      color = $9 ; flag = $10; pos = $11;
      if (flag == "leftmost") { start = pos; thickStart = pos}
      if (flag == "rightmost") { stop = pos; thickStop = pos}
      #name = chr"|"start"|"stop
      name = chr ","  start ","  stop ","  thickStart  "," thickStop
      print chr, start, stop, name, score, strand, thickStart, thickStop, color
    }'
}


counts_fr ()
{
  local infile=$1
  local infileMax=
  if [ $# -ge 2 ]; then
    infileMax=$2
  fi

  cat $infile \
  | sed -e 's/\t/;/g' \
  | awk -F ";" 'BEGIN{OFS="\t"}{
      print $1, $7 ,$3, $0
  }' \
  | sort $SORT_OPT_BED \
  > ${tmpdir}/counts_fr.region_for_fwd.bed


  cat $infile \
  | sed -e 's/\t/;/g' \
  | awk -F ";" 'BEGIN{OFS="\t"}{
      print $1, $2 ,$8, $0
  }' \
  | sort $SORT_OPT_BED \
  > ${tmpdir}/counts_fr.region_for_rev.bed


  for strand in fwd rev
  do
    chunkN=$( expr  $( cat ${tmpdir}/counts_fr.region_for_${strand}.bed | wc -l ) / $splitLines + 1 )
    split -n "r/${chunkN}" ${tmpdir}/counts_fr.region_for_${strand}.bed ${tmpdir}/counts_fr.region_for_${strand}.bed.split.

    ls ${tmpdir}/counts_fr.region_for_${strand}.bed.split.* \
    | xargs -P ${parallel} -I % bigWigAverageOverBed ${tmpdir}/infile.${strand}.bw  % %.OUT

    cat ${tmpdir}/counts_fr.region_for_${strand}.bed.split.*.OUT \
    | cut -f 1,4 \
    | sort $SORT_OPT_NAME \
    >  ${tmpdir}/counts_fr.${strand}.txt

    rm -f cat ${tmpdir}/counts_fr.region_for_${strand}.bed.split.* &

    if [ -n "${infileMax}" ]; then
      gunzip -c ${infileMax} \
      | awk --assign strand=$strand '{ 
          if((strand =="fwd")&&($6 == "+")){print};
          if((strand =="rev")&&($6 == "-")){print}; 
        }' \
      | sort $SORT_OPT_BED \
      | intersectBed -sorted -wa -wb -a ${tmpdir}/counts_fr.region_for_${strand}.bed -b stdin \
      | sort $SORT_OPT_NAME \
      | groupBy -grp 4 -opCols 9 -ops max \
      | sort $SORT_OPT_NAME \
      > ${tmpdir}/max_fr.${strand}.txt &
    fi
  done

  wait

  #chr22   17141513        17142052        chr22,17141513,17142052 0       .       17141713        17142052        0,0,0   1       23
  join -t "	" ${tmpdir}/counts_fr.fwd.txt ${tmpdir}/counts_fr.rev.txt \
  > ${tmpdir}/counts_fr.joined.txt 

  if [ -n "${infileMax}" ]; then
    cat ${tmpdir}/counts_fr.joined.txt \
    | sort $SORT_OPT_NAME \
    | join -t "	" -a 1  -e 0 -o 0,1.2,1.3,2.2 /dev/stdin ${tmpdir}/max_fr.fwd.txt \
    | sort $SORT_OPT_NAME \
    | join -t "	" -a 1  -e 0 -o 0,1.2,1.3,1.4,2.2 /dev/stdin ${tmpdir}/max_fr.rev.txt \
    > ${tmpdir}/counts_fr.joined.txt.tmp
    mv --force ${tmpdir}/counts_fr.joined.txt.tmp ${tmpdir}/counts_fr.joined.txt
  fi


  cat ${tmpdir}/counts_fr.joined.txt \
  | sed -e 's/;/\t/g' \
  | awk 'BEGIN{OFS="\t"}{
      chr = $1; start = $2; stop = $3; name = $4; score = $5; strand = $6;
      thickStart = $7; thickStop = $8; color = $9; counts_fwd = $10; counts_rev = $11; max_fwd = $12 ; max_rev = $13 ;
      counts = counts_fwd + counts_rev
      if (counts == 0){next}
      directionality = (counts_fwd - counts_rev) / counts
      directionality_abs = directionality
      if (directionality_abs < 0) { directionality_abs = -1 * directionality_abs}
      name = name"|counts:"counts"|countsFwd:"counts_fwd"|countsRev:"counts_rev"|directionality:"directionality
      if ( max_fwd != "" ) {
        max_ctss = max_fwd;
        if ( max_ctss < max_rev ){max_ctss = max_rev}
        name = name"|ctssMax:"max_ctss"|ctssMaxFwd:"max_fwd"|ctssMaxRev:"max_rev
      }

      color = sprintf( "%d,0,%d", 127 + 127 * directionality , 127 - 127 * directionality )
      #print chr, start, stop, name, directionality_abs, strand, thickStart, thickStop, color
      print chr, start, stop, name, 0, strand, thickStart, thickStop, color
    }'
}


#--------------------------------------------------------
# main
#--------------------------------------------------------

cmd_bam2ctss ()
{
  mapQ=20
  parallel=8
  filter_window=20
  filter_target_base=G
  ratio_Gaddition=0.89

  ### handle options
  while getopts i:q:p:w:b:f:r:g: opt
  do
    case ${opt} in
    i) infile=${OPTARG};;
    q) mapQ=${OPTARG};;
    p) parallel=${OPTARG};;
    w) filter_window=${OPTARG};;
    b) filter_target_base=${OPTARG};;
    f) outfile_full=${OPTARG};;
    r) ratio_Gaddition=${OPTARG};;
    g) genome_fa=${OPTARG};;
    *) usage;;
    esac
  done

  if [ ! -n "${infile-}" ]; then usage; fi
  if [ ! -n "${genome_fa-}" ]; then usage; fi

  ### setup tmpdir
  tmpdir=$(mktemp -d -p ${TMPDIR:-/tmp})
  trap "test -d $tmpdir && rm -rf $tmpdir" 0 1 2 3 15

  splitBam2UnmatchMatchOthers
  correctG

  if [ -n "${outfile_full-}" ]; then
    ( cd ${tmpdir} ; tar cvf - . ) | gzip -c  > $outfile_full
  fi
  #cp -f ${tmpdir}/correctG.bed.gz ${outfile}
  gunzip -c ${tmpdir}/correctG.bed.gz
}


cmd_total ()
{
  ### handle options
  parallel=20
  while getopts i:c:p:o: opt
  do
    case ${opt} in
    i) infiles=${OPTARG};;
    c) chrom_sizes=${OPTARG};;
    p) parallel=${OPTARG};;
    o) out_prefix=${OPTARG};;
    *) usage;;
    esac
  done
  if [ ! -n "${infiles-}" ]; then usage; fi
  if [ ! -n "${chrom_sizes-}" ]; then usage; fi
  if [ ! -n "${out_prefix-}" ]; then usage; fi

  printf "### total\n"  >&2

  ### setup for later
  tmpdir=$(mktemp -d -p ${TMPDIR:-/tmp})
  trap "test -d $tmpdir && rm -rf $tmpdir" 0 1 2 3 15
  mkdir -p ${tmpdir}/each
  mkdir -p ${tmpdir}/TpmEach
  mkdir -p ${tmpdir}/merge
  SORT_OPT_BASE="--batch-size=100"
  export SORT_OPT_BED="${SORT_OPT_BASE} -k1,1 -k2,2n -k3,3n"
  export SORT_OPT_BED_NAME="${SORT_OPT_BASE} -k4,4"
  export SORT_OPT_NAME="${SORT_OPT_BASE} -k1,1"

  export -f ctssbed_to_bg

  echo $infiles | sed -e 's/,/\n/g' > ${tmpdir}/infilesList.txt

  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "gunzip -c {} | ctssbed_to_bg + > ${tmpdir}/each/\$(basename {}).fwd.bg"
  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "gunzip -c {} | ctssbed_to_bg - > ${tmpdir}/each/\$(basename {}).rev.bg"

  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "bedGraphToBigWig ${tmpdir}/each/\$(basename {}).fwd.bg $chrom_sizes ${tmpdir}/each/\$(basename {}).fwd.bw"
  cat ${tmpdir}/infilesList.txt | xargs  -P ${parallel} -I {} bash -c \
    "bedGraphToBigWig ${tmpdir}/each/\$(basename {}).rev.bg $chrom_sizes ${tmpdir}/each/\$(basename {}).rev.bw"

  export -f ctssGzBed_to_TpmBg
  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "ctssGzBed_to_TpmBg {} + > ${tmpdir}/TpmEach/\$(basename {}).tpm.fwd.bg"
  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "ctssGzBed_to_TpmBg {} - > ${tmpdir}/TpmEach/\$(basename {}).tpm.rev.bg"

  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "bedGraphToBigWig ${tmpdir}/TpmEach/\$(basename {}).tpm.fwd.bg $chrom_sizes ${tmpdir}/TpmEach/\$(basename {}).tpm.fwd.bw"
  cat ${tmpdir}/infilesList.txt | xargs -P ${parallel} -I {} bash -c \
    "bedGraphToBigWig ${tmpdir}/TpmEach/\$(basename {}).tpm.rev.bg $chrom_sizes ${tmpdir}/TpmEach/\$(basename {}).tpm.rev.bw"

  find  ${tmpdir}/each -name '*.fwd.bw' -type f -print > ${tmpdir}/merge/infileF.list
  find  ${tmpdir}/each -name '*.rev.bw' -type f -print > ${tmpdir}/merge/infileR.list

  bigWigMerge -inList ${tmpdir}/merge/infileF.list /dev/stdout \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3,".",$4,"+"}' \
  > ${tmpdir}/merge/totalF.bed &

  bigWigMerge -inList ${tmpdir}/merge/infileR.list /dev/stdout \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3,".",$4,"-"}' \
  > ${tmpdir}/merge/totalR.bed &

  bigWigMerge -max -inList ${tmpdir}/merge/infileF.list /dev/stdout \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3,".",$4,"+"}' \
  > ${tmpdir}/merge/maxF.bed &

  bigWigMerge -max -inList ${tmpdir}/merge/infileR.list /dev/stdout \
  | awk 'BEGIN{OFS="\t"}{print $1,$2,$3,".",$4,"-"}' \
  > ${tmpdir}/merge/maxR.bed &

  wait

  for operation in total max
  do
    cat ${tmpdir}/merge/${operation}F.bed ${tmpdir}/merge/${operation}R.bed \
    | sort $SORT_OPT_BED \
    | awk 'BEGIN{OFS="\t"}
      {
        for (start=$2; start < $3; start++ ) 
        {
          print $1, start, start + 1, $4, $5, $6
        }
      }' \
    | gzip -c > ${tmpdir}/merge/${operation}.ctss.bed.gz

    gunzip -c ${tmpdir}/merge/${operation}.ctss.bed.gz \
    | ctssbed_to_bg + > ${tmpdir}/merge/${operation}.ctss.fwd.bg
    gunzip -c ${tmpdir}/merge/${operation}.ctss.bed.gz \
    | ctssbed_to_bg - > ${tmpdir}/merge/${operation}.ctss.rev.bg
    bedGraphToBigWig ${tmpdir}/merge/${operation}.ctss.fwd.bg $chrom_sizes ${tmpdir}/merge/${operation}.ctss.fwd.bw
    bedGraphToBigWig ${tmpdir}/merge/${operation}.ctss.rev.bg $chrom_sizes ${tmpdir}/merge/${operation}.ctss.rev.bw

    for suffix in .bed.gz .fwd.bw .rev.bw
    do
      mv -f ${tmpdir}/merge/${operation}.ctss${suffix} ${out_prefix}_${operation}.ctss${suffix}
    done
  done

  #(cd ${tmpdir}/each/;  ls *.bw | sort | xargs tar cavf - ) > ${out_prefix}_each.ctss.bw.tar
  (cd ${tmpdir}/each/;  ls *.bw | sort | xargs -I % tar --append --file=/dev/stdout %  ) > ${out_prefix}_each.ctss.bw.tar
  (cd ${tmpdir}/TpmEach/;  ls *.bw | sort | xargs -I % tar --append --file=/dev/stdout %  ) > ${out_prefix}_each.ctssTpm.bw.tar
}


cmd_call ()
{
  ### handle options
  parallel=20
  window_size=200
  export splitLines=10000000
  infileMax=''
  infileEach=''
  prog_compression=gzip
  while getopts i:m:c:w:p:z: opt
  do
    case ${opt} in
    i) infile=${OPTARG};;
    m) infileMax=${OPTARG};;
    c) chrom_sizes=${OPTARG};;
    w) window_size=${OPTARG};;
    p) parallel=${OPTARG};;
    z) prog_compression=${OPTARG};;
    *) usage;;
    esac
  done
  if [ ! -n "${infile-}" ]; then usage; fi
  if [ ! -n "${chrom_sizes-}" ]; then usage; fi

  printf "### call\n"  >&2

  ### setup for later
  tmpdir=$(mktemp -d -p ${TMPDIR:-/tmp})
  trap "test -d $tmpdir && rm -rf $tmpdir" 0 1 2 3 15
  window_half_size=$(( $window_size / 2 ))
  window_double_size=$(( $window_size * 2 ))

  SORT_OPT_BASE="--batch-size=100"
  SORT_OPT_BED="${SORT_OPT_BASE} -k1,1 -k2,2n -k3,3n"
  SORT_OPT_BED_NAME="${SORT_OPT_BASE} -k4,4"
  SORT_OPT_NAME="${SORT_OPT_BASE} -k1,1"

  PROG_COMP="$prog_compression -c"
  PROG_DECOMP="$prog_compression -d"
  if [ "${prog_compression}" = "zstd"  ]; then
    PROG_COMP="$PROG_COMP -T${parallel} "
  fi

  printf "### call: prepare target positions\n" >&2 
  prep_input $infile $window_double_size

  printf "### call: compute neighbouring signals\n" >&2
  accumulate_neiboring_signals \
    ${tmpdir}/potential_center.bg.COMP \
    ${tmpdir}/infile.fwd.bw \
    ${tmpdir}/infile.rev.bw \
    $window_size \
  | $PROG_COMP \
  > ${tmpdir}/potential_center.txt.COMP

  printf "### call: select divergent regions\n" >&2
  cat ${tmpdir}/potential_center.txt.COMP \
  | $PROG_DECOMP \
  | classify_convergent_divergent \
      ${tmpdir}/potential_center_conv.bed \
      ${tmpdir}/potential_center_divergent.bed

  printf "### call: find cores with left/right boundaries\n"  >&2
  find_max_scores \
    ${tmpdir}/potential_center_divergent.bed \
    ${tmpdir}/infile.density.fwd.bg \
    ${tmpdir}/infile.density.rev.bg \
    $window_size \
  > ${tmpdir}/potential_center_divergent_with_core.bed

  printf "### call: tighten\n"  >&2
  tighten_unidirectional ${tmpdir}/potential_center_divergent_with_core.bed \
  > ${tmpdir}/potential_center_divergent_with_core_tight.bed

  printf "### call: counts_fr\n"  >&2
  total=$( gunzip -c ${infile} | awk '{sum += $5 * ($3-$2)}END{print sum}' )
  counts_fr ${tmpdir}/potential_center_divergent_with_core_tight.bed ${infileMax} \
  | awk --assign total=$total 'BEGIN{OFS="\t"}{
      if (match( $4, /counts:[-.0-9,]+/)) {
        c = substr($4, RSTART, RLENGTH)
        sub("counts:", "", c)
        c += 0
      }
      tpm = 1e6 * c / total
      $4 = $4"|total:"total"|tpm:"tpm
      $5 = tpm
      print
    }'
}



cmd_eachcount ()
{
  ### handle options
  parallel=20
  infile=
  infileEach=
  while getopts i:e:p:o: opt
  do
    case ${opt} in
    i) infile=${OPTARG};;
    e) infileEach=${OPTARG};;
    p) parallel=${OPTARG};;
    o) out_prefix=${OPTARG};;
    *) usage;;
    esac
  done
  if [ ! -n "${infile-}" ]; then usage; fi
  if [ ! -n "${infileEach-}" ]; then usage; fi
  if [ ! -n "${out_prefix-}" ]; then usage; fi
  printf "### eachcount\n"  >&2

  ### setup for later
  tmpdir=$(mktemp -d -p ${TMPDIR:-/tmp})
  trap "test -d $tmpdir && rm -rf $tmpdir" 0 1 2 3 15

  mkdir -p ${tmpdir}/each
  tar xvf ${infileEach} -C ${tmpdir}/each/


  ###
  ### assign tentative name
  ###
  gunzip -c ${infile} \
  | grep -v ^# \
  | sort -k1,1 -k2,2n \
  | awk '{printf "LN%012d\t%s\n", NR, $0}' \
  > ${tmpdir}/LN_infile.txt

  ###
  ### prep regions (core + extended for forward or reverse)
  ###
  cat ${tmpdir}/LN_infile.txt \
  | awk 'BEGIN{OFS="\t"}{
    chr=$2;start=$3;stop=$4;core_start=$8;core_stop=$9;name=$1
    print chr, core_start, stop, name
  }' > ${tmpdir}/fwd.bed

  cat ${tmpdir}/LN_infile.txt \
  | awk 'BEGIN{OFS="\t"}{
    chr=$2;start=$3;stop=$4;core_start=$8;core_stop=$9;name=$1
    print chr, start, core_stop, name
  }' > ${tmpdir}/rev.bed


  ###
  ### prep totals
  ###
  find ${tmpdir}/each/ -name '*.fwd.bw' \
  | xargs -P ${parallel} -I % sh -c \
     "bigWigToBedGraph % /dev/stdout | awk '{sum += \$4 * (\$3 - \$2)}END{print \"%,\"sum}' > %.totalFwd.txt " \

  find ${tmpdir}/each/ -name '*.fwd.bw.totalFwd.txt' \
  | xargs -I % cat % \
  | sed 's/.fwd.bw,/\t/'  \
  | sed 's/^.*\///'  \
  | sort -k1,1 \
  > ${tmpdir}/totalsFwd.txt


  find ${tmpdir}/each/ -name '*.rev.bw' \
  | xargs -P ${parallel} -I % sh -c \
     "bigWigToBedGraph % /dev/stdout | awk '{sum += \$4 * (\$3 - \$2)}END{print \"%,\"sum}' > %.totalRev.txt " \

  find ${tmpdir}/each/ -name '*.rev.bw.totalRev.txt' \
  | xargs -I % cat % \
  | sed 's/.rev.bw,/\t/'  \
  | sed 's/^.*\///'  \
  | sort -k1,1 \
  > ${tmpdir}/totalsRev.txt

  join -t "	" ${tmpdir}/totalsFwd.txt ${tmpdir}/totalsRev.txt \
  | awk 'BEGIN{OFS="\t"}{print $1,$2+$3}' \
  > ${tmpdir}/totals.txt


  ###
  ### counts in parallel
  ###
  cut -f 1 ${tmpdir}/totals.txt \
  | xargs -P ${parallel} -I % sh -c  \
    "bigWigAverageOverBed ${tmpdir}/each/%.fwd.bw ${tmpdir}/fwd.bed ${tmpdir}/each/%.fwd.bw.txt; gzip ${tmpdir}/each/%.fwd.bw.txt"

  cut -f 1 ${tmpdir}/totals.txt \
  | xargs -P ${parallel} -I % sh -c  \
    "bigWigAverageOverBed ${tmpdir}/each/%.rev.bw ${tmpdir}/rev.bed ${tmpdir}/each/%.rev.bw.txt; gzip ${tmpdir}/each/%.rev.bw.txt"


  ###
  ### merge each counts 
  ###
  gunzip -c ${tmpdir}/each/$( head -1 ${tmpdir}/totals.txt | cut -f 1 ).fwd.bw.txt.gz \
  | cut -f 1 \
  | tee ${tmpdir}/count.fwd.txt \
  > ${tmpdir}/count.rev.txt 

  for X in $( cat ${tmpdir}/totals.txt | cut -f 1  )
  do
    X=${tmpdir}/each/${X}.fwd.bw.txt.gz
    gunzip -c $X \
    | cut -f 1,4 \
    | join -t "	" ${tmpdir}/count.fwd.txt - \
    > ${tmpdir}/count.fwd.txt.tmp
    mv -f ${tmpdir}/count.fwd.txt.tmp ${tmpdir}/count.fwd.txt
  done

  for X in $( cat ${tmpdir}/totals.txt | cut -f 1  )
  do
    X=${tmpdir}/each/${X}.rev.bw.txt.gz
    gunzip -c $X \
    | cut -f 1,4 \
    | join -t "	" ${tmpdir}/count.rev.txt - \
    > ${tmpdir}/count.rev.txt.tmp
    mv -f ${tmpdir}/count.rev.txt.tmp ${tmpdir}/count.rev.txt
  done


  ###
  ### merge fwd & rev
  ###
  cat ${tmpdir}/count.fwd.txt \
  | awk '{buf=$2;for(i=3;i <=NF; i++){buf=buf","$i};print $1"\t"buf}' \
  > ${tmpdir}/count.fwd.txt.tmp
  mv -f ${tmpdir}/count.fwd.txt.tmp ${tmpdir}/count.fwd.txt


  cat ${tmpdir}/count.rev.txt \
  | awk '{buf=$2;for(i=3;i <=NF; i++){buf=buf","$i};print $1"\t"buf}' \
  > ${tmpdir}/count.rev.txt.tmp
  mv -f ${tmpdir}/count.rev.txt.tmp ${tmpdir}/count.rev.txt


  join -t "	" \
    ${tmpdir}/count.fwd.txt \
    ${tmpdir}/count.rev.txt \
  | sort -k1,1 \
  | awk 'BEGIN{OFS="\t"}{
      fwdN=split($2,eachCountsFwd,",");
      revN=split($3,eachCountsRev,",");
      i = 1
      eachCounts = eachCountsFwd[i] + eachCountsRev[i]
      for (i=2; i<=fwdN; i++) {
        eachCounts = eachCounts","(eachCountsFwd[i] + eachCountsRev[i])
      }
      print $1, eachCounts, $2, $3
    }' \
  > ${tmpdir}/count.fwdrev.txt


  cut -f 1 ${tmpdir}/totals.txt \
  | xargs -L 1 echo -n " " \
  | sed -e 's/ \+/,/g' \
  | sed -e 's/^,//' \
  | awk '{
      printf("#chrom\tchromStart\tchromEnd\tname\tscore\tstrand\tthickStart\tthickEnd\titemRgb\tcounts[%s]\tfwdCounts[.]\trevCounts[.]\n" , $0 )
    }' \
  > ${tmpdir}/out_eachcounts.bed9pls3


  cat ${tmpdir}/count.fwdrev.txt \
  | join -t "	" ${tmpdir}/LN_infile.txt  - \
  | cut -f 2- \
  >> ${tmpdir}/out_eachcounts.bed9pls3


  gzip -c ${tmpdir}/out_eachcounts.bed9pls3 > ${out_prefix}_eachcounts.bed9pls3.gz
  cp -f ${tmpdir}/totals.txt ${out_prefix}_eachcounts_totals.txt


  cat <<EOF | R --slave | gzip -c > ${out_prefix}_eachcounts.txt.gz
  library(tidyverse)

  buf = read_tsv("${out_prefix}_eachcounts_totals.txt", col_names=F, comment = "#")
  totals = unlist( buf[,2] )
  names(totals) = unlist( buf[,1] )

  bed = read_tsv("${out_prefix}_eachcounts.bed9pls3.gz", col_names=T, comment = "")
  colnames(bed)[10] = "counts"

  counts = bed %>% 
    select("name", counts) %>%
    separate( counts, sep=",", into=names(totals) )

  counts = rbind(
    c( "01STAT:TOTAL", totals ),
    counts
  )

  write.table(counts, sep="\t", quote = F,row.names=F)
EOF


}



cmd_filter ()
{
  ### handle options
  max_directionality=1
  min_directionality=0
  max_counts=-1
  min_counts=4
  max_tpm=-1
  min_tpm=0
  min_counts_in_each_strand=0
  min_ctssMax=0
  min_ctssMax_in_each_strand=0
  max_length=-1
  min_length=5
  invert_match="false"

  while getopts D:d:C:c:T:t:e:x:y:l:L:v opt
  do
    case ${opt} in
    D) max_directionality=${OPTARG};;
    d) min_directionality=${OPTARG};;
    C) max_counts=${OPTARG};;
    c) min_counts=${OPTARG};;
    T) max_tpm=${OPTARG};;
    t) min_tpm=${OPTARG};;
    e) min_counts_in_each_strand=${OPTARG};;
    x) min_ctssMax=${OPTARG};;
    y) min_ctssMax_in_each_strand=${OPTARG};;
    L) max_length=${OPTARG};;
    l) min_length=${OPTARG};;
    v) invert_match="true";;
    *) usage;;
    esac
  done

  printf "### filter\n"  >&2


  awk \
    --assign max_directionality=$max_directionality \
    --assign min_directionality=$min_directionality \
    --assign max_counts=$max_counts \
    --assign min_counts=$min_counts \
    --assign max_tpm=$max_tpm \
    --assign min_tpm=$min_tpm \
    --assign min_counts_in_each_strand=$min_counts_in_each_strand \
    --assign min_ctssMax=$min_ctssMax \
    --assign min_ctssMax_in_each_strand=$min_ctssMax_in_each_strand \
    --assign max_length=$max_length \
    --assign min_length=$min_length \
    --assign invert_match=$invert_match \
  'BEGIN{OFS="\t"}{

    if (match( $0, /directionality:[-.0-9]+/)) {
      s = substr($0, RSTART, RLENGTH)
      sub("directionality:", "", s)
      d = s + 0;
      if (d < 0) { d = d * -1}
    }

    if (match( $0, /counts:[-.0-9]+/)) {
      c = substr($0, RSTART, RLENGTH)
      sub("counts:", "", c)
      c += 0;
    }
    if (match( $0, /countsFwd:[-.0-9]+/)) {
      f = substr($0, RSTART, RLENGTH)
      sub("countsFwd:", "", f)
      f += 0;
    }
    if (match( $0, /countsRev:[-.0-9]+/)) {
      r = substr($0, RSTART, RLENGTH)
      sub("countsRev:", "", r)
      r += 0;
    }

    cm = 0; cmf = 0 ; cmr = 0;
    if (match( $0, /ctssMax:[-.0-9]+/)) {
      cm = substr($0, RSTART, RLENGTH)
      sub("ctssMax:", "", cm)
      cm += 0;
    }
    if (match( $0, /ctssMaxFwd:[-.0-9]+/)) {
      cmf = substr($0, RSTART, RLENGTH)
      sub("ctssMaxFwd:", "", cmf)
      cmf += 0;
    }
    if (match( $0, /ctssMaxRev:[-.0-9]+/)) {
      cmr = substr($0, RSTART, RLENGTH)
      sub("ctssMaxRev:", "", cmr)
      cmr += 0;
    }
    if (match( $0, /tpm:[-.0-9]+/)) {
      tpm = substr($0, RSTART, RLENGTH)
      sub("tpm:", "", tpm)
      tpm += 0;
    }

    if ( ( cm == 0 ) && ( min_ctssMax > 0) ) {
      print "Error: No ctssMax found. Related filters cannot be used.\n" > "/dev/stderr"
      exit 1
    }
    if ( ( cm == 0 ) && ( min_ctssMax_in_each_strand > 0) ) {
      print "Error: No ctssMax found. Related filters cannot be used.\n" > "/dev/stderr"
      exit 1
    }

    len = $3 - $2

    flagM = "true"
    if      ( d > max_directionality )           { flagM = "false" }
    else if ( d < min_directionality )           { flagM = "false" }

    else if ( ( max_counts >= 0) &&
              ( c > max_counts ) )               { flagM = "false" }
    else if ( c < min_counts )                   { flagM = "false" }

    else if ( ( max_tpm >= 0  ) &&
              ( tpm > max_tpm ) )                { flagM = "false" }
    else if ( tpm < min_tpm )                    { flagM = "false" }

    else if ( f < min_counts_in_each_strand )    { flagM = "false" }
    else if ( r < min_counts_in_each_strand )    { flagM = "false" }

    else if ( cm < min_ctssMax )                 { flagM = "false" }
    else if ( cmf < min_ctssMax_in_each_strand ) { flagM = "false" }
    else if ( cmr < min_ctssMax_in_each_strand ) { flagM = "false" }

    else if ( ( max_length >= 0  ) &&
              ( len > max_length ) )                { flagM = "false" }
    else if ( len < min_length )                    { flagM = "false" }


    # invert
    if ( invert_match == "true" ) {
      if ( flagM == "true" ) { flagM = "false" } else { flagM = "true" }
    }
    if ( flagM == "true" ) { print }
  }'
}



cmd_classify ()
{
  ### handle options
  els_pls_cutoff=2
  while getopts e: opt
  do
    case ${opt} in
    e) els_pls_cutoff=${OPTARG};;
    *) usage;;
   esac
  done

  printf "### classify\n"  >&2

  awk --assign els_pls_cutoff=$els_pls_cutoff 'BEGIN{
    OFS="\t"

    # -- 11 color bins for PLA and ELA (in R) --
    #> c2rgb = function(c) paste(col2rgb(c)[,1],collapse=",")
    #> colorRampPalette(c("red","black","blue"))(11) %>% sapply( c2rgb ) %>% paste(collapse="|")
    #[1] "255,0,0|204,0,0|153,0,0|101,0,0|50,0,0|0,0,0|0,0,51|0,0,102|0,0,153|0,0,204|0,0,255"
    #> colorRampPalette(c("lightsalmon","yellow","skyblue"))(11) %>% sapply( c2rgb ) %>% paste(collapse="|")
    #[1] "255,160,122|255,179,97|255,198,73|255,217,48|255,236,24|255,255,0|230,245,47|207,235,94|182,225,141|159,215,188|135,206,235"
    str = "255,0,0|204,0,0|153,0,0|101,0,0|50,0,0|0,0,0|0,0,51|0,0,102|0,0,153|0,0,204|0,0,255"
    split(str, colPla, "|")
    str = "255,160,122|255,179,97|255,198,73|255,217,48|255,236,24|255,255,0|230,245,47|207,235,94|182,225,141|159,215,188|135,206,235"
    split(str, colEla, "|")
  }{
    # obtain TPM
    if (match( $0, /tpm:[-.0-9]+/)) {
      tpm = substr($0, RSTART, RLENGTH)
      sub("tpm:", "", tpm)
      tpm += 0;
    }

    # obtain directionality from color code
    #match( $9, /^[0-9]+,/)
    #r = substr($9, RSTART, RLENGTH - 1)
    #match( $9, /,[0-9]+$/)
    #b = substr($9, RSTART + 1, RLENGTH-1)

    # obtain directionality
    match( $4, /countsFwd:[0-9.eE+]+/)
    r = substr($4, RSTART + 10, RLENGTH - 10)
    match( $4, /countsRev:[0-9.eE+]+/)
    b = substr($4, RSTART + 10, RLENGTH - 10)

    rb = ( r - b ) / ( r + b )
    bin = 6 - sprintf("%d", rb * 5 )

    if (tpm >= els_pls_cutoff ) {
      $4 = $4 "|class:PLA"
      $9 = colPla[bin]
    } else {
      $4 = $4 "|class:ELA"
      $9 = colEla[bin]
    }
    print
  }'
}


cmd_run ()
{

  ### handle options
  window_size=200
  parallel=20
  prog_compression=gzip
  min_length=5
  min_counts=4
  min_tpm=0
  els_pls_cutoff=2

  while getopts i:c:o:w:l:n:t:p:z:e: opt
  do
    case ${opt} in
    i) infilesList=${OPTARG};;
    c) chrom_sizes=${OPTARG};;
    o) out_prefix=${OPTARG};;
    w) window_size=${OPTARG};;
    l) min_length=${OPTARG};;
    n) min_counts=${OPTARG};;
    t) min_tpm=${OPTARG};;
    p) parallel=${OPTARG};;
    e) els_pls_cutoff=${OPTARG};;
    z) prog_compression=${OPTARG};;
    *) usage;;
   esac
  done

  if [ ! -n "${infilesList-}" ]; then usage; fi
  if [ ! -n "${chrom_sizes-}" ]; then usage; fi
  if [ ! -n "${out_prefix-}" ]; then usage; fi

  cat <<EOF > ${out_prefix}_param.txt
-i $infilesList
-c $chrom_sizes
-o $out_prefix
-w $window_size
-l $min_length
-n $min_counts
-t $min_tpm
-p $parallel
-e $els_pls_cutoff
-z $prog_compression
EOF

  $0 total \
    -i $infilesList \
    -c $chrom_sizes \
    -o ${out_prefix} \
    -p ${parallel}

  $0 call \
    -i ${out_prefix}_total.ctss.bed.gz \
    -c ${chrom_sizes} \
    -w ${window_size} \
    -m ${out_prefix}_max.ctss.bed.gz \
    -p ${parallel} \
    -z ${prog_compression} \
  | gzip -c > ${out_prefix}_region.bed.gz

  gunzip -c ${out_prefix}_region.bed.gz \
  | $0 filter -l ${min_length} -c ${min_counts} -t ${min_tpm} \
  | $0 classify -e ${els_pls_cutoff} \
  | gzip -c > ${out_prefix}_region_filter_classify.bed.gz

  $0 eachcount \
    -i ${out_prefix}_region_filter_classify.bed.gz \
    -o ${out_prefix}_region_filter_classify \
    -e ${out_prefix}_each.ctss.bw.tar \
    -p ${parallel}
}


#--------------------------------------------------------
# main
#--------------------------------------------------------

case "${1:-}" in
  bam2ctss)
    shift;
    cmd_bam2ctss "$@"
    ;;
  run)
    shift;
    cmd_run "$@"
    ;;
  total)
    shift;
    cmd_total "$@"
    ;;
  call)
    shift;
    cmd_call "$@"
    ;;
  filter)
    shift;
    cmd_filter "$@"
    ;;
  classify)
    shift;
    cmd_classify "$@"
    ;;
  eachcount)
    shift;
    cmd_eachcount "$@"
    ;;
  version|-v|--version)
    echo "CREate ${VERSION}"
    ;;
  *)
    usage
    ;;
esac




